### ISSUE TITLE
Improve e2e screenshot stability

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/carbon-app#1004]
Two issues in this [PR](https://github.com/bancorprotocol/carbon-app/pull/1003) with screenshots:

1. Some screenshots are showing visual diff when there are small pixel changes
2. When some screenshots are taken, the cursor may be on top of a tooltip, showing it as part of the screenshot

Goal is to make sure that screenshots are only committed when there are visual diffs (as much as possible)

**Comment by GrandSchtroumpf** [comment]
Also we might need to wait for the transition to end for : 
- tooltip & modal after detached
- button after enabled
