### ISSUE TITLE
It takes changes in too many places to get the app to work on another network

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-app#1024]
In order to run the app with another network the developer should:
- set the RPC under .env - VITE_CHAIN_RPC_URL 
- modifying the files under  /src/services/web3 to reflect the correct tokens and addresses
- once the backend is setup - its URL should be set in src/utils/carbonApi.ts

We should ideally have a single place for all these settings

**Comment by GrandSchtroumpf** [comment]
Thinks to take into account: 
- rpc urls
- Alchemy id
- token list
- backend url

Ideally we want to have development & production environments
