### ISSUE TITLE
After clicking Trade nav option the BACK button is useless

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-app#1038]
Visit the app, let's say you're in Explorer
click Trade in nav bar
> you are redirected to a specific pair URL
click back

expected:
you get back to Explorer

actual:
you get back to trade - and immediately get redirected to the specific pair URL

Please fix by replacing history when redirecting and not pushing to history

**Comment by tiagofilipenunes** [comment]
Same thing happens for the simulate page.

1. Open app, go to some random tab like explorer
2. Go to simulate
3. Go back

Expected: Go back to trade
Actual: Stays in simulate
