### ISSUE TITLE
Simulator - Bugs

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#1039]
## Bugs

- [x] #1077
Flow:
1. open simulator page 
2. input both ETH and USDC budgets
3. click on "Start simulation" CTA
expected: Estimated gains show USDC token symbol on the right of the USDC amount
actual: Estimated gains show USDC token symbol on the left of the USDC amount

- [x] #1078
Flow:
1. open simulator page 
2. select two tokens that have no price chart history(00 and 0xagon for example)
expected: The following design is implemented and a user can't start the simulation [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=13105%3A108243&mode=design&t=w0jvvTf11J063fsw-1)
actual: The above design isn't implemented and user can click on “Start Simulation” CTA

- [x] #1082

- [x] “Buy or Sell” and “With” titles in the token selection fields are barely visible
implement the following design: [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=12264%3A34900&mode=design&t=2IhwtFQbCDahJF6U-1) @tiagofilipenunes 
https://github.com/bancorprotocol/carbon-app/pull/1058

- [x] pair toggle doesn't update pre populated prices
Flow:
1. open simulator for ETH/USDC
2. we pre-populate the buy and sell ranges
3. click the toggle to switch pair direction, which will be USDC/ETH
expected: prices to be updated to fit the new pair direction
actual: prices stay as before which position them off the price chart

- [x] There is no padding between the “Start simulation” CTA and the button of the page
Flow:
1. open simulator page
2. scroll to the bottom of the page
expected: There should be a padding between the “Start simulation” CTA and the bottom of the simulator page
actual: There is no free space between the “Start simulation” CTA and the bottom of the simulator page

- [x] If one of the budgets is not entered, it is displayed as "NAN" on the results page
Flow:
1. open simulator page
2. insert both buy and sell ETH prices and budget data but leave the USDC token budget field empty
3. click on "Start simulation" CTA
expected: The USDC budget will be displayed as "0" on the simulation result page
actual: The USDC budget  is displayed as "NAN" on the simulation result page

- [x] Remove "TBD" from the ROI tooltip on the simulation result page
expected: tooltip text-  "Learn how ROI is calculated"
actual: tooltip text - "TBD. Learn how ROI is calculated"

- [x] Don't show how much the user will receive if the order is 100 filled and at what average price below the budget field
Flow:
1. open simulator page 
2. input ETH and USDC budgets
expected: No text is shown below each of the budget fields
actual: User sees how much he will receive if the order is 100 filled and at what average price

- [x] price gap between frontend and csv -> **update: not an issue, bid and ask factor in the fee**
create eth/usdc simulation
input prices
SellHigh 2500-2600
buyLow 1900-2200
csv prices
ask: 2505.01002 
bid: 1896.2

- [x] Hide simulator disclaimer for 15 mins after pressing "I understand" isn't working
  - [x] Calculation using daysjs().unix() should be in seconds and not milliseconds
  - [x] simDisclaimerLastSeen doesn't persist between refreshes

**Comment by tiagofilipenunes** [comment]
Bug
- [ ] When opening the simulator results directly on new private tab or browser that has never opened the app, there is an error.

Flow
1. Open private tab 
2. Go to https://app.carbondefi.xyz/simulator/result?baseToken=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&quoteToken=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&buyMin=2129.1045702185235&buyMax=2395.2426414958389&buyBudget=2000&buyIsRange=true&sellMin=2927.5187840504697&sellMax=3193.6568553277851&sellBudget=100&sellIsRange=true&start=1676711645&end=1707815645
3. See error. Refresh. Now works.
