### ISSUE TITLE
Remove well-known tokens

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#1042]
We currently use well-known tokens in the app like that : `config.tokens.WETH`.
In an effort to make the application more reusable for other network we should reduce the amount of well-known tokens to the strict minimal (ZERO, ETH)
As part of this task we should update the interface in the config file.

**Comment by tiagofilipenunes** [comment]
This was handled as part of https://github.com/bancorprotocol/carbon-app/pull/1188
