### ISSUE TITLE
Estimated gains show token symbol on the left of the amount

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/carbon-app#1077]
Flow:
open simulator page
input both ETH and USDC budgets
click on "Start simulation" CTA
expected: Estimated gains show USDC token symbol on the right of the USDC amount
actual: Estimated gains show USDC token symbol on the left of the USDC amount

**Comment by GrandSchtroumpf** [comment]
We'll keep it on the left because animation makes the symbol jumps
