### ISSUE TITLE
SEI issues

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#1213]
- [ ] Market price in edit overlapping strategy is 0. It should be derived from existing strategy if no external market price available
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/033a9b88-ea01-42e7-8214-748ffa26b1f0)
- [x] Remove link to simulate in menu
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/510a962e-7d74-4b4b-b1a9-dac7d9c2d125)
- [x] Redirect request to /simulate to prevent user to access it

- [x] When duplicating and back the menu do not display the same items
https://github.com/bancorprotocol/carbon-app/assets/8143464/1f1ac169-6c75-46b5-967c-67c97ef0f415

**Comment by tiagofilipenunes** [comment]
> When duplicating and back the menu do not display the same items
https://github.com/bancorprotocol/carbon-app/assets/8143464/1f1ac169-6c75-46b5-967c-67c97ef0f415

Related to issue https://github.com/bancorprotocol/carbon-app/issues/1183
