### ISSUE TITLE
Create strategy - overlapping strategy has a "recurring" tag

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#1257]
flow:
create a new overlapping strategy
on the page where you set prices, it says "recurring".
<img width="455" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/40430285/982f713b-49e7-4ff6-9705-99b0c54f9f9c">

updated:
replace it with "overlapping"

**Comment by tiagofilipenunes** [comment]
Duplicated, closed in favour of #1007
