### ISSUE TITLE
[Overlapping] Edit Price Graph is incoherent

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#1288]
Currently the graph is incoherent:
- It display "User defined market price" when price is either set by the user OR is calculated from geomean
- Displayed market price is the one used by the form (either user defined, calculated or external market price)
- Marginal price is always calculated based on the market price & min/max. It doesn't reflect the current state of the marginal price.

https://github.com/bancorprotocol/carbon-app/assets/8143464/723a4fc2-5bdb-4bc6-b5cd-e64405f5e2f9

**Comment by ashachaf** [comment]
@Costa769 please check if this is still relevant given last pr by @GrandSchtroumpf

**Comment by Costa769** [comment]
@ashachaf Looks like it was resolved
