### ISSUE TITLE
[SENTRY] QuotaExceededError

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/carbon-app#1290]
Error from Sentry:`The quota has been exceeded` when setting localStorage cachedDump in src/hooks/useCarbonInit.ts:

```
const persistSdkCacheDump = async () => {
  console.log('SDK Cache dumped into local storage');
  const cachedDump = await carbonSDK.getCacheDump();
  lsService.setItem('sdkCompressedCacheData', cachedDump, true);
};
```

**Comment by zavelevsky** [comment]
I didn't see it there, it actually worked fine on Safari incognito. What failed to access local storage was an iframe related to wallet connect

**Comment by tiagofilipenunes** [comment]
This is the sentry error: https://bprotocol-foundation.sentry.io/issues/5462663218/?project=4505074572197888&query=is%3Aunresolved+issue.category%3Aerror+quota&referrer=issue-stream&statsPeriod=30d&stream_index=0

Comes from utils/managedLocalStorage.ts

**Comment by tiagofilipenunes** [comment]
I believe the migration process has reduced the frequency of this problem occurring, as the keys with "carbon-v1" had not been migrated and users had both "carbon-v1" and "carbon-v1.1" key prefixes in the localStorage before the process was implemented.

This issue has also not been observed for 2 months. Closing for now until escalating.

Related to #1294
