### ISSUE TITLE
[Trade] Trading View refresh on each subpage change

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#1419]
On the trade page, when we switch to a new subpage (form or explorer), the trading view iframe refresh.

https://github.com/user-attachments/assets/573f9c88-ff42-49ab-bba2-6d77f0e61a8c

**Comment by ashachaf** [comment]
doesnt happen as often as the design has changed.
still happens when you change `strategy type` 

https://github.com/user-attachments/assets/3dbe9464-2cff-4c97-826c-6c81874df380
