### ISSUE TITLE
Update Icons and Animations to Reflect Brand Colors

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#1535]
Update the icons and animations to utilize brand colors for consistency.

### 1. Icons on portfolio page

- Platform benefits icons on the portfolio page ( icons are shown when wallet is not connected)[Designs](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=4740-90491&t=AVfWqHNSYxwzweYd-1)

<img width="426" alt="image" src="https://github.com/user-attachments/assets/3c1884a7-0e7c-4aa7-aa79-65c814cb3582">

- Create Strategy icon 
<img width="329" alt="image" src="https://github.com/user-attachments/assets/315191ef-afc2-484a-825c-224c220da438">

### 2. Connect wallet animation

- The green line animation on the top of the popup
<img width="420" alt="image" src="https://github.com/user-attachments/assets/1611c9ee-6d11-4a61-8b4b-58957995e920">

### 3. Selected checkbox

- Selected checkbox across entire app (wallet connect popup, filters, etc)
<img width="260" alt="image" src="https://github.com/user-attachments/assets/586b6424-8672-4c3b-9a76-9f048bd5b6be">

**Comment by tiagofilipenunes** [comment]
Closed by #1540
