### ISSUE TITLE
Debug Feature: Link to Tenderly Dashboard in Notifications

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/carbon-app#267]
when on tenderly, the etherscan link in notifications should point to the tenderly dashboard

**Comment by tiagofilipenunes** [comment]
A direct link to the tenderly explorer has the following structure:

https://dashboard.tenderly.co/${TENDERLY_ACCOUNT_ID}/${TENDERLY_PROJECT_ID}/fork/${TENDERLY_FORK_ID}/simulation/${transaction_id}

Example:
https://dashboard.tenderly.co/bancor/carbon-test-forks/fork/0e61cc3c-8069-4281-94a0-ec2ae7f0fdfe/simulation/6879d30c-0679-4c52-8a02-9e6b6c89b05d

Fork ID can be easily obtained from the RPC; the account id and project id would have to be defined in the /debug page. Looking through the tenderly docs, it isn't possible to get the transaction ID without using the Tenderly Simulation API. It is also not possible to link directly to the explorer using the transaction hash.

Therefore, to implement this issue, the following would be required:
- Add project and account id forms in /debug
- Get latest transaction id from Simulation API (which also needs the project and account id)
- Add the tenderly explorer page directly to the notifications.

@pingustar mentioned that this feature was more useful in the earlier stages of the app development, so I suggest to either close it or move it to the backlog as its implementation is in my view over-complicated for its benefit.

@zavelevsky @ashachaf
