### ISSUE TITLE
Trade - token search 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#467]
current:
searching a token that does not exist, show blank area.

updated:
https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=1894-37463&t=UXSWUcYppXN2fNjU-4

IF search by token symbol cannot find a token, suggest searching by address.
IF search by address cannot find a token, suggest creating a strategy -> on click, open create strategy with "base" as the address used by the user.

**Comment by tiagofilipenunes** [comment]
@ashachaf Can this issue be closed?

"Create a strategy" when selecting a pair with no orders is already suggested in the trade page
![image](https://github.com/bancorprotocol/carbon-app/assets/66181828/7a6a0ca0-aea9-43ad-8a78-a83a781e1d31)

Searching by address is now suggested too on pages other than the trade page
![image](https://github.com/bancorprotocol/carbon-app/assets/66181828/a4d25b8d-5adf-4afb-9547-28408fd4b938)
