### ISSUE TITLE
Strategy overview - mobile "manage" menu design

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#484]
## Strategy overview menu
click "manage" on a strategy overview and the menu should be updated to show up like this:
https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=4335-75879&t=JmwMYeB22wLMQ6cO-4

**Comment by tiagofilipenunes** [comment]
@ashachaf Is this still blocked?
