### ISSUE TITLE
Switch to Decimal.js and retire BigNumber.js

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/carbon-app#533]

**Comment by tiagofilipenunes** [comment]
Blocked by #431

**Comment by GrandSchtroumpf** [comment]
For future reference. We want decimal.js because
- We use Decimal.js in the SDK
- We can specifiy precision on Decimal.js
- BigNumber have precision limitations

As a second step we could start working with BigInt, but it's wider PR as it involves changing the SDK too.
