### ISSUE TITLE
Add support for Trust Wallet

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#545]
trust wallet currently works and can be used in the app.
however, it is not ideal.

web:
currently, we only support trust wallet via wallet connect. 
please follow this to integrate direct integration to trust wallet
https://developer.trustwallet.com/trust-wallet-browser-extension/extension-guide

mobile:
currently, we allow connecting when clicking the 'metamask' icon. this is working but incorrect implementation.
we should aim to identify the user wallet directly (when using the wallet native browser on mobile).
please follow this to improve the integration
https://github.com/trustwallet/web3-react-trust-wallet

**Comment by pingustar** [comment]
Adding native support for trust wallet along-side our current authentication logic which is handled by the react-web3 library is possible but going to be a pain.

If we are going through the pain and process of writing a native implementation, I suggest we explore the option of creating an official connector for the web3-react library as PR to their repo.

Benefits are:

- we can keep current auth logic as is and simply add a new connector to the list
- others will be able to use the connector, saving them the headache

Cons are:

- probably a bit more work
- going through the process of PR review, approval, package release might take a while

Opportunities:

- possibility for joint venture with trust wallet?!

**Comment by ashachaf** [comment]
Can you revisit the react-web3 library to see if they already support trust wallet?
I do see it in their code
