### ISSUE TITLE
Resolve console warnings on production

### ISSUE THREAD

**Issue by oznasi1** [bancorprotocol/carbon-app#664]
- [ ] Resolve warning on prod 
- [ ] Check out trade page rendering - changing input causing re render of all page

![telegram-cloud-photo-size-4-6028395421149281009-y](https://github.com/bancorprotocol/carbon-app/assets/24458541/5a8acafc-07de-473f-8ec8-44a35a9f9496)

**Comment by ashachaf** [comment]
@zavelevsky is this still relevant?

**Comment by zavelevsky** [comment]
closing as stale
