### ISSUE TITLE
Token Logos are not always round

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/carbon-app#669]
we dont always make the token logo a circle, leading to ugly white borders

![telegram-cloud-photo-size-4-6037269265964448044-y](https://github.com/bancorprotocol/carbon-app/assets/7262066/9a46156b-4c51-432f-8b65-37bab697279c)

**Comment by tiagofilipenunes** [comment]
Also happening in the Strategies page:



![Image](https://github.com/bancorprotocol/carbon-app/assets/66181828/14c3dbc7-95eb-4c15-985b-310f6c88522b)

And the portfolio page



![Image](https://github.com/bancorprotocol/carbon-app/assets/66181828/325ed8eb-31a6-4e15-b84d-4c6254192486)

**Comment by pingustar** [comment]
@tiagofilipenunes pr is merged but issue still open and I see missing round logo here:

![image](https://github.com/bancorprotocol/carbon-app/assets/7262066/559ee181-b344-4953-90c3-794e49e3ded7)

**Comment by tiagofilipenunes** [comment]
@pingustar got merged into #756
