### ISSUE TITLE
Fiat currency display rules

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#671]
Change the way we display fiat values on the website for all the supported currencies

### Current:

If currency = USD, CAD or AUD
Display  "$" symbol before the number and the currency code after the number
Else
Display the currency code after the number

**Examples:**

USD: $100 USD
AUD: $100 AUD
CAD: $100 CAD
EUR: 100 EUR
JPY: 100 JPY

### Updated:
**IF** one of the fiat currencies is selected (USD, EUR ,GBP, JPY, AUD, CAD, CHF and CNH)
User the mapping table below to display a currency symbol & currency code before the amount:

USD-$ 
EUR-€
GBP-£
JPY-¥
AUD-A$
CAD-CA$
CHF-CHF
CNH-CNH

**Examples:**
USD: $100
EUR: €100
GBP: £100
JPY:  ¥100
AUD: A$100
CAD: CA$100
CHF: CHF 100
CNH: CNH 100

**ELSE** (if crypto currency is selected)
Display the currency code after the number

**Examples:**
ETH:  100 ETH

**Comment by GrandSchtroumpf** [comment]
We can use `Int.NumberFormat` for that ([Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat))
