### ISSUE TITLE
Set/edit prices page bugs

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#677]
- [ ] Max & Min tooltip texts are incorrect

When creating a new strategy , on the page where the user is asked to set prices or on editing an existing strategy prices  page , given that the "range " option is selected, we display a tool tip on mouse over the min and max price input indication. The tooltip display quote token instead of base token

Flow:

1. Create ETH(base)-USDC(quote) "2 ranges" order type strategy 
2. On set prices page with "range" option selected,  mouse hover over min and max price input indications in both buy and sell range input fields
3. Tooltip is displayed.

Expected tooltip text:

Buy min tooltip text: "The lowest price to buy ETH at."
Buy max tooltip text:"The highest price to buy ETH at."
Sell min tooltip text: "The lowest price to sell ETH at."
Sell max tooltip text: "The highest price to sell ETH at."

Actual tooltip text:

Buy min tooltip text: "The lowest price to buy USDC at."
Buy max tooltip text:"The highest price to buy USDC at."
Sell min tooltip text: "The lowest price to sell USDC at."
Sell max tooltip text: "The highest price to sell USDC at."

- [ ] Error message with capital letter "P"

Flow:

1. On the set/edit prices pages with "range" option selected enter min amount that is greater than max amount in the range price fields
2. Error message is displayed

Actual error message:
"Max Price must be higher than min price and not zero"

Expected error message:
"Max price must be higher than min price and not zero"

**Comment by ashachaf** [comment]
@Costa769 is this still relevant?

**Comment by Costa769** [comment]
> @Costa769 is this still relevant?

Yes

**Comment by Costa769** [comment]
The first part of the task with tooltip text fix is done, but the still a capital “P” in the error message
