### ISSUE TITLE
Add undercut option to duplicate strategy flow

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#702]
### Summary

When a user duplicates a strategy, we want to provide them with an option to undercut the original strategy's prices, allowing their newly duplicated strategy to be fulfilled ahead of the original one.

### Designs
[Duplicate modal with two options](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=7040%3A120470&mode=design&t=m3nqlEZS1VKGl4dm-1)

### Flow
When the user clicks on the duplicate strategy icon, we want to show a modal with two options.

1. Duplicate as is
2. Undercut the strategy

IF "Duplicate as is" is selected (same behavior as the current duplicate strategy icon on click).
- Navigate to the set prices page with the strategy tokens and type preselected, and prices and budgets prefilled with the values of the original strategy.

IF "Undercut the strategy" is selected
- Navigate to the set prices page with the strategy tokens and type preselected, and budgets prefilled with the values of the original strategy. 
- Undercut the prices by 0.1%.
- Formula: 
-- {Undercut token buy price} = {Original token buy price}+ {Original token buy price} * 0.1/100
-- {Undercut token sell price} = {Original token sell price}- {Original token sell price} * 0.1/100
- Examples:
-- User duplicates a ETH/USDC strategy with range buy ETH for min 1600 USDC- max 1700 USDC  and limit sell ETH for 
     1800 USDC prices 
-- Undercut token min buy price = 1600+1600 * 0.1/100= 1601.6
-- Undercut token max buy price = 1700+1700 * 0.1/100= 1701.7
-- Undercut token sell price = 1800-1800 * 0.1/100= 1798.2

**Comment by zavelevsky** [comment]
@ashachaf @Costa769 do we want different analytics events depending on the option the user selected?
