### ISSUE TITLE
token logo bug

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#711]
some token logo images are square.
for some reason, we do not apply the circular mask on some cases.

<img width="1240" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/40430285/382f3c22-5a86-40df-972a-7324456d4349">
<img width="539" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/40430285/359d90f9-7d4a-477f-b907-2bfd34493b83">

**Comment by pingustar** [comment]
I believe this has been fixed by @zavelevsky
