### ISSUE TITLE
Create/Edit Strategy - include "100% fill" outcome

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#746]
## Summary

As a user, when i create or edit an order, i would like to know the expected acquired amount as well as the average price if the order is 100% filled.

## Design:
[Create strategy with price&budget inputs](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78020&mode=design&t=qtBtJlXQlQidT1jn-1)
[Create strategy with empty buy price&budget](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8583%3A50365&mode=design&t=qtBtJlXQlQidT1jn-1)
[Create strategy -insufficient budget](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8583%3A50654&mode=design&t=qtBtJlXQlQidT1jn-1)
[Edit prices](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78496&mode=design&t=SN5ZTSRPhGhcRwPE-1)
[Deposit funds](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78630&mode=design&t=SN5ZTSRPhGhcRwPE-1)
[Withdraw funds](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8592%3A51053&mode=design&t=qtBtJlXQlQidT1jn-1)

## Overview

1. Displaying acquired amount and the average price when order is 100% filled is relevant when:
- creating a new strategy
- editing prices of an existing order (as the 100% returns will change)
- deposit/withdraw (as the budget is changing)
2. The acquired amount and average price will change according to the the user's price and budget inputs
3. The acquired amount and the average price will be displayed for both recurring and disposable strategy types
4. The acquired amount and the average price are calculated and displayed separately for both buy and sell orders
6. The acquired amount calculation is performed only for the current iteration of buy and sell orders using current order price and budget.
7. Any subsequent trades and profits that could potentially refill the strategy budget in the future are not considered in the acquired amount calculation.
8.  When displaying acquired amount and the average price adhere to the current numbers display format

### Average price
Order average price is calculated using a geometric mean formula.
GeoMean = (lowRate * highRate)^0.5
Example:
- Limit price
-- lowRate = 100
-- highRate = 100
-- GeoMean = (100 * 100)^0.5 = 100
- Range price
-- lowRate = 100
-- highRate = 250
-- GeoMean = (100 * 250)^0.5 = 158.1138830084

Please be aware that when calculating the GeoMean, the 'lowRate' and 'highRate' prices in the formula should correspond to the user's input prices. In situations where we need to refer to prices obtained from a contract, particularly for buy orders where they represent the selling price of the quote token in exchange for the base token, a slightly modified formula should be employed
GeoMean = (1/lowRate * 1/highRate)^0.5

### Acquired amount
Using the GeoMean value, it is possible to calculate the acquired amount.
Note that there is a different calculation for buy and sell orders since prices are shown in quote asset. 
#### Order type rules
IF Sell {BaseToken} order, AcquiredAmount = orderBudget*GeoMean
IF Buy {BaseToken} order, AcquiredAmount = orderBudget/GeoMean
Example:
- Sell ETH for USDC order
-- Price: 1630
-- Budget: 2 ETH
-- AcquiredAmount = 2 * 1630 = 3260 USDC
- Buy ETH with USDC order
-- Price: 1580
-- Budget: 5000 USDC
-- AcquiredAmount = 5000/1580 = 3.164556962

## Create new strategy
The new text with the acquired amount and the average price will show up under sell and buy budget fields for both disposable or recurring strategies once the user enters both price and budget.
### Display rules
IF buyPrice AND buyBudget values >0 display the following text:
**Below buy budget field for buy order**
-- "If the order is 100% filled, you will receive {acquired base token amount} at an average price of {average price in quote token} per 1 {base token}. Learn More"

IF sellPrice AND sellBudget values >0 display the following text:
**Below sell budget field for sell order**
-- "If the order is 100% filled, you will receive {acquired quote token amount} at an average price of {average price in quote token} per 1 {base token}. Learn More"
### More details
- "Learn More" link on click- open a new tab with the following URL- https://faq.carbondefi.xyz/order-execution/100-fill-estimation (url is not live yet but this is the url it will have)
- The acquired amount and the average price calculation should be performed with every change in the price or budget input value, without requiring the user to exit the input field
- In case the user has selected a range order and entered the budget and only one of the min-max prices(instead of both), do not display the text.
- If the user enters a budget amount greater than the available wallet amount, display the text according to the user's input amount below the "insufficient balance" error message [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8583%3A50654&mode=design&t=V3JsvmxyeGTAHmcD-1)

#### Buy order example
- Create a new recurring strategy with ETH/USDC
- Create a buy range order
- Set ETH buying price at 1600 USDC
- Set buy budget amount to 3200 USDC

**Calculations:**
- GeoMean = (lowRate * highRate)^0.5 = (1,600 * 1600)^0.5 = 1600 USDC
- AcquiredAmount: IF Buy order, AcquiredAmount = buyBudget/GeoMean = 3200/1600 = 2 ETH
- Display the following text below the buy budget field:
 "If the order is 100% filled, you will receive 2 ETH at an average price of 1,600 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78021&mode=design&t=GWOmM2jcmUhd0GPR-1)

#### Sell order example
- Create a new recurring strategy with ETH/USDC
- Create a sell range order
- Set selling price range between 1800-1900 USDC
- Set sell budget amount to 2.5 ETH

**Calculations:**
- GeoMean = (lowRate*highRate)^0.5 = (1800 * 1900)^0.5 = 1849.3242008907 USDC
- AcquiredAmount: IF Sell order, AcquiredAmount = sellBudget * GeoMean = 2.5 * 1849.3242008907 = 4623.31050222675 USDC
- Display the following text below the sell budget field:
"If the order is 100% filled, you will receive 4,623.310502 USDC at an average price of 1,849.324200 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78021&mode=design&t=GWOmM2jcmUhd0GPR-1)

## Edit prices
- Click on manage-> edit rates on an existing strategy
- **IF** price AND allocated budget >0, immediately show the text with the acquired amount and the average price below the buy/sell allocated budget section accordingly
-- Display the identical text to the one found in the 'Create new strategy' section
- **IF** a user deletes the price (set it to 0 or delete), apply the rule to hide the text 

### Edit buy order price example
- Click on edit rates on the disposable ETH/USDC strategy
- The strategy parameters are as follows:
- ETH buying price is 1500 USDC
- Allocated buy budget amount is 4500 USDC

#### Default view
**Calculations:**
- GeoMean = (lowRate*highRate)^0.5 = (1500 * 1500)^0.5 = 1500 USDC
- AcquiredAmount: IF Buy order, AcquiredAmount = buyBudget/GeoMean = 4500/1500 = 3 ETH
- Display the following text below the buy budget field:
 "If the order is 100% filled, you will receive 3 ETH at an average price of 1500 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78496&mode=design&t=ZPWZerXkDMz5AOe4-1)

#### Price edit
Update price value:
- New: 1550 USDC
**Calculations:**
- GeoMean = (lowRate * highRate)^0.5 = (1550 * 1550)^0.5 = 1550 USDC
- AcquiredAmount: IF Buy order, AcquiredAmount = buyBudget/GeoMean = 4500/1550 = 2.9032258065 ETH
- Display the following text below the buy budget field:
 "If the order is 100% filled, you will receive 2.903225 ETH at an average price of 1550 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8726%3A144744&mode=design&t=84vkxngjHUHi9kG2-1)

## Deposit/withdraw budget
At present, buy and sell prices are not displayed on the deposit and withdraw pages. As buy and sell prices are integral to calculating acquired amount and average price values, we intend to exhibit them on the page beneath the allocated buy and sell budgets. [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78630&mode=design&t=GWOmM2jcmUhd0GPR-1) 

To provide clarity to the user about the budget being utilized for calculating acquired amount and average price values, we will display distinct versions of the text beneath the sell/buy allocated budget&price sections.

### Display rules
- Click on manage-> deposit/withdraw budget on an existing strategy
- **IF** price AND allocated budget >0, immediately show the text with the acquired amount and the average price below the buy/sell allocated budget&price section accordingly
-- Display the identical text to the one found in the 'Create new strategy' section

Given the user has entered deposit/withdraw amount
**New budget calculation**
For deposit: New budget =Allocated budget + UserInput
For withdraw: New budget =Allocated budget - UserInput

- **IF** price AND new budget >0, change the text to indicate that a new budget is being utilized for calculating acquired amount and average price values
   **Below allocated buy budget&price section**
   -- "Based on updated budget, If the order is 100% filled, you will receive {acquired base token amount} at an average 
         price of {average price in quote token} per 1 {base token}. Learn More"
   **Below allocated sell budget&price section**
   -- "Based on updated budget, If the order is 100% filled, you will receive {acquired quote token amount} at an average 
         price of {average price in quote token} per 1 {base token}. Learn More"
**ELSE**
- **IF** price or new budget =0
   -- Apply the rule to hide the text
- **IF** new budget <0 (if the user enters a withdrawal amount greater than the available budget amount)
   -- Apply the rule to hide the text and display only the current error message 

### Deposit budget example
- Click on manage-> deposit budget to an existing  ETH/USDC strategy
- The strategy parameters are as follows:
- ETH buying price is 1400 USDC
- Allocated buy budget amount is 0 USDC

IF buyBudget>0, 
[False], do not show the text with the acquired amount and the average price below the allocated buy budget&price section [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8517%3A78630&mode=design&t=84vkxngjHUHi9kG2-1)
 
#### Update budget
- User input: 2000 USDC
- IF deposit, NewBuyBudget = currentBudget + UserInput
-- NewBuyBudget = currentBudget+userInputBudget = 0+2000 = 2000

**Calculations:**
- GeoMean = (lowRate * highRate)^0.5 = (1400 * 1400)^0.5 = 1400 USDC
- AcquiredAmount: IF Buy order, AcquiredAmount = newBuyBudget/GeoMean = 2000/1400 = 1.4285714286 ETH
- Display the following text below the allocated budget&price section:
 "Based on updated budget, If the order is 100% filled, you will receive 1.428571 ETH at an average price of 1,400 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8726%3A145416&mode=design&t=84vkxngjHUHi9kG2-1)

### Withdraw budget example
- Click on manage-> withdraw budget from an existing  ETH/USDC strategy
- The strategy parameters are as follows:
- ETH buying price is 1300 USDC
- Allocated buy budget amount is 3000 USDC

#### Default view
- GeoMean = (lowRate*highRate)^0.5 = (1300 * 1300)^0.5 = 1300 USDC
- AcquiredAmount: IF Buy order, AcquiredAmount = buyBudget/GeoMean = 3000/1300 = 2.3076923077 ETH
- Display the following text below the allocated budget&price section:
 "If the order is 100% filled, you will receive 2.307692 ETH at an average price of 1300 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8592%3A51053&mode=design&t=84vkxngjHUHi9kG2-1)

#### Update budget
- User input: 1000 USDC
- IF withdraw, NewBuyBudget = currentBudget - UserInput
-- NewBuyBudget = currentBudget-userInputBudget = 3000-1000 = 2000

- GeoMean = (lowRate*highRate)^0.5 = (1300 * 1300)^0.5 = 1300 USDC
- AcquiredAmount: IF Buy order, AcquiredAmount = buyBudget/GeoMean = 2000/1300 = 1.5384615385 ETH
- Display the following text below the allocated budget&price section:
 "Based on updated budget, If the order is 100% filled, you will receive 1.5384615 ETH at an average price of 1300 USDC per 1 ETH. Learn More" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8726%3A145854&mode=design&t=84vkxngjHUHi9kG2-1)

**Comment by GrandSchtroumpf** [comment]
@ashachaf Should we display a text if the user withdraw everything ?
