### ISSUE TITLE
Add a link to the carbon DEX page on CoinGecko

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#751]
### Summary
Carbon was listed as a DEX on CoinGecko. We would like to add a link from a Carbon app to the Carbon DEX page on CoinGecko

### Overview
1. Add a "Carbon on CoinGecko" link below the Blog link on the Carbon app menu
<img width="236" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/127974452/2f2a868a-6259-4c3c-9d85-e391d5a31df5">

2. On click-> open the specified URL in a new browser tab
https://www.coingecko.com/en/exchanges/carbon

**Comment by tiagofilipenunes** [comment]
@Costa769 

Just to confirm - it's this url right?

https://www.coingecko.com/en/exchanges/carbon

**Comment by Costa769** [comment]
> @Costa769
> 
> Just to confirm - it's this url right?
> 
> https://www.coingecko.com/en/exchanges/carbon

Yes, added it to the task
