### ISSUE TITLE
Explorer - tool tip updates

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#755]
please make the following text changes in the explorer page:
NOTE: make sure this change is only apply on the explorer page and not on the "my strategies" page

1. strategy active/inactive tool tip
current text: Your strategy is active and ready
updated text: This strategy is currently active and ready to process trades
<img width="400" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/40430285/4eba7350-b4e6-4813-9387-e9ec79afff5c">

2. manage notification tool tip
current text: Get notified when someone trades against your strategy
updated text: Get notifies when someone trades against this strategy 
![image](https://github.com/bancorprotocol/carbon-app/assets/40430285/a1719e99-16b1-43dd-a02f-89212b4ad701)

**Comment by tiagofilipenunes** [comment]
@ashachaf I assumed the manage notification tooltip is
"Get notified when someone trades against this strategy"

Also, what about the other tooltip states?

Current implementation below, feel free to suggest changes:

| State    | Tooltip MyStrategy                                                                | Tooltip Explorer                                                   |
| -------- | --------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| Active   | Your strategy is active and ready                                                 | This strategy is currently active and ready to process trades      |
| NoBudget | Your strategy has no associated funds. Consider depositing funds to activate it.  | This strategy has no associated funds and will not process trades. |
| Paused   | Your strategy is currently paused. Edit the prices to activate it.                | This strategy is currently paused and will not process trades.     |
| Inactive | Your strategy is currently inactive. Consider activating it with funds and rates. | This strategy is currently inactive and will not process trades.   |
