### ISSUE TITLE
Bug: Currency sub-menu selector not updating after changing currency

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/carbon-app#761]
When a user selects a currency from the currency sub-menu modal, the currency symbol selector doesn’t immediately change until the menu modal is re-opened or the window is refreshed.

How to replicate: Press “Currency” to enter the currency sub-menu, select a different currency. Press “Currency” again to go to the currency sub-menu. The latest selected currency is still the previous one.

Example: Selecting two different currencies doesn’t update the chosen one in the selector.

https://github.com/bancorprotocol/carbon-app/assets/66181828/759e5f7a-670e-4ac7-b710-cd1d1b59da4d

**Comment by pingustar** [comment]
@Murad544 is looking into this
