### ISSUE TITLE
[Feedback] First experience

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#764]
I'm using this issue to put all my feedback

## UX
- [ ] Add warning when leaving a form page with unsaved content
- [ ] Display the market price alongside the percent in the strategy form
- [ ] Maybe prefill price input with current market price
- [ ] Optional budget: Add sentence explaining that carbon will use token bought to sell
- [ ] Renew strategy page should have previous price I think
- [ ] Click on the address on top right corner should copy address
- [ ] Would be nice to have ENS address search on the explorer

## UI
- [ ] Unexpected rounded number in tooltip for limit price & price range strategy.
- [ ] Not the same sizing, font size & weight for switch/tab
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/891d9919-815b-4104-882e-2d412cdd8577)
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/ee9e155f-7186-431f-b09f-2ab8af66912c)
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/ae5d09a6-d697-489c-be93-ddd05b2345ec)
- [ ] Not same layout organization for search
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/53f3693d-9f82-420c-bd77-af5e2407615f)
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/c829ae00-42f7-48be-b605-498369b46f44)
- Responsiveness between 850px & 1100px
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/c40147ce-a414-4b86-acdb-0e8a07dc29ce)
- [ ] Add more information about not found trade page
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/51a8c910-871f-4d9e-896a-37113129d121)

## a11y
- [ ] Don't use `button` in `a` ([documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#technical_summary))
- [ ] Better to use `fieldset` & `radio` in switch & filter component to have free keyboard navigation and better event handling
- [x] Use `nav` for main navigation and tab navigation with the correct aria-label
- [x] Add `aria-current="page"` on active link in main nav & `aria-current="location"` on tab navigation
- [ ] Search section should be inside a `<search role="search">` tag and input should have either `type="search"` or `role="searchbox"`
- [ ] Reduce animation motion & blur when browser's has prefers-reduced-motion: reduced
- [ ] Filter dialog should handle Escape keyboard to close
- [ ] Focus enter menus & selects even when it's not opened
- [ ] Add roles on menu widget ([Documentation](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/))
- [ ] In graph on portfolio, add caption or accessibility.description in the option of the pie chart to let the user know the total balance.
- [ ] In table on portfolio, on each clickable row, add tabindex="0" & handle "Enter" & "space" key to forward the click
- [ ] In table on portfolio, on each non-clickable row, remove hover effect

## Performance
- [ ] Move Google Tag Manager into web worker (we can use [Partytown](https://partytown.builder.io/))

**Comment by zavelevsky** [comment]
> * Renew strategy page should have previous price I think

This is problematic since we don't have this information in the contracts.
I can think of a few ways to achieve this:
- scan events to figure out last prices prior to pausing it 
- keep it in local storage (suboptimal as it's not a complete solution)
- some backend

**Comment by pingustar** [comment]
@GrandSchtroumpf 

great feedback!

I am gonna close this issue as part of my cleanup.

Please take a few minutes in tomorrows sync to go over each item on the list with us and then lets create new independent issues out of the items that need it.
