### ISSUE TITLE
Explore IndexedDB implementation

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#772]
Currently we use local storage to cache data from the SDK. There are many issues involved:
- data must be serialized
- versioning is hard
- local storage is synchronous, so it blocks operations priorities in the browser

A good alternative seems to be IndexedDB. It provides feature to address the issue above, but is known to have a hard API to work with.
Let's see if we can implement it in a reasonable time.

Some resources:
- https://web.dev/indexeddb/
- https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API
- https://github.com/jakearchibald/idb

**Comment by GrandSchtroumpf** [comment]
Advantages:
- Supports versioning and migration
- Supports advance queries (pagination, filter, ...)
- Runs in web worker
- Uses structured clone instead of JSON.parse (support Date, bigint, ArrayTyped, ...)

Disadvantages:
- Weird API, but the library `idb` fixes it.

**Comment by ashachaf** [comment]
@zavelevsky

**Comment by zavelevsky** [comment]
> @zavelevsky

@ashachaf feel free to ignore issues label as "under the hood"
