### ISSUE TITLE
[Bug] Error on range 0 - 100 not displayed

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#812]
How to reproduce : 
1. create a strategy with range
2. enter 0 in min then 100 in max
No error is displayed
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/3bb1eb2f-0ed5-46eb-a579-b67981cafdd4)

3. change 0 to 1, an 0 again
A error is displayed
![image](https://github.com/bancorprotocol/carbon-app/assets/8143464/cdc8959a-5e20-494e-87ee-bb1c612a1e12)

Expected behavior: on 2 the error should be displayed

**Comment by ashachaf** [comment]
@GrandSchtroumpf i believe this is no longer relevant
