### ISSUE TITLE
Search string in My Strategies affects results in Explorer

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-app#825]
Search input on strategies page applies to the search results on the explorer page

### Steps to reproduce:

1. Go to my strategies page
2. Type "dddd" in the search field
3. Go to explorer page
4. Search for ETH/USDC token pair

**Current result**
User sees "We couldn't find any strategies" page

**Expected result**
User sees all the ETH/USDC strategies

**Comment by GrandSchtroumpf** [comment]
How to reproduce
- Navigate to "My Strategy"
- Write "ddd" in the searchbar
- Navigate to "Explorer"
- Select "Pair Wallet" -> "Eth / dai"
- No strategy displayed
Expected behavior: We should see strategies for eth/dai
