### ISSUE TITLE
No loading state for "View Owner's Strategies" - seems disabled

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-app#828]
Go to Explorer and open the Manage menu of a strategy.

The "View Owner's Strategies" option is disabled for a few seconds and then becomes enabled (after owner information is retrieved). This causes the user to believe the option is disabled.

We should either show a clear loading indication - or just make the option enabled and once the user clicks we fetch the owner information (making it clear that we do so) and when ready apply the search

**Comment by Nagendra88688** [comment]
hey @zavelevsky , can i pick up this fix?

**Comment by zavelevsky** [comment]
> hey @zavelevsky , can i pick up this fix?

Hi @Nagendra88688 - I'm happy to learn that you're interested in contributing!

This issue is currently assigned to a Product Manager - for him to decide on the expected user experience. Once @Costa769 adds specific specs to this issue we can proceed.

I suggest you watch this issue - once it's decided you can let us know if you're available and up to it.

Seeing that you're interested, I'll  try to make sure I'm adding "good first issue" labels to issues that are ready to be worked on (and are good first issues :) )

**Comment by Nagendra88688** [comment]
Thanks you @zavelevsky

**Comment by ashachaf** [comment]
duplicated issue
