### ISSUE TITLE
Dymanic Theme

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#888]
Build a dynamic theme to allow : 
- [ ] changing the colors
- [ ] changing icons
- [ ] changing some text

**Comment by zavelevsky** [comment]
@GrandSchtroumpf please make sure Product understand this proposal and then either make this an actionable issue with details and specifics - or close it

**Comment by GrandSchtroumpf** [comment]
This was an issue when we discussed white labeling the application. I'll close as it's not relevant anymore.
