### ISSUE TITLE
Explorer - update URL to display token address

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#897]
current URL format:
https://app.carbondefi.xyz/explorer/token-pair/dai_eth

updated URL format:
https://app.carbondefi.xyz/explorer/token-pair/base={daiAddress}&quote={ethAddress}
https://app.carbondefi.xyz/explorer/token-pair/base=0x6B175474E89094C44Da98b954EedeAC495271d0F&quote=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE

(this is the format used in the trade page)

**Comment by zavelevsky** [comment]
The strong requirement here is to not rely on token symbols and display addresses in the URL.

**Comment by zavelevsky** [comment]
In general - we will run on networks where for example there are 2 valid tokens with the USDC symbol
