### ISSUE TITLE
Update Router version

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#899]
Use TanStack router beta : https://tanstack.com/router/v1/docs/installation

**Comment by zavelevsky** [comment]
Step 1: drop in replacement for react-location

Step 2: put its more powerful API to use and in general use it as if we started from scratch. Try to better address things that we compromised for such as not being able to use hooks from the router config, resolving paths using search params validators. See if out of the box capabilities it presents are helpful to us. See if it can better integrate with tanstack query for its cache and route loading.
