### ISSUE TITLE
Number display - small number handling

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#929]
This issue is taking a piece out of issue #727.

# Overview
we would like to update the way small numbers are displayed. 
currently, we show 6 decimals and if the number is smaller we show "<0.000001"
the updated approach would expose the small numbers to the user in an updated manner.

### Exceptions

- Percentage numbers ->display logic for percentage numbers remains unchanged, and percentages below 0.01% will continue to be displayed as they are currently, i.e., "<0.01%."
- Input fields->both user input and automatically prefilled values will continue to  display full numbers without any changes.
- When mouse over a subscribe number and the tooltip is displayed, display full number in the tooltip without applying the subscribe format
- 
## Mockup

[Designs](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11296%3A86130&mode=design&t=nxpkUEwRyQ6TTWyU-1)

## Specifications
**IF** {integer digits}=0 AND {number of first decimals that are 0}>=3 do the following:
- Display first decimal as 0
- Count the number of 0 decimals from the first decimal up to the first decimal that is not 0
- Display the number as a subscript next to the first 0 decimal (if counted 6 zeros, the number needs to be 6 and the first zero is visible)
- Take 5 decimals starting from the first decimal that is not 0 and display them after the first 0 decimal
<img width="317" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/127974452/f4377247-3c08-4080-9308-5c3ec4dca8a0">

**Examples(prices displayed in USD):**
<img width="323" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/127974452/8d538007-f7df-4f50-adda-1cdb529b0431">

**Comment by GrandSchtroumpf** [comment]
After discussing with @Costa769 we decided to : 
- Apply full value for tooltip except the one on the strategy card's graph
- Prices should follow this pattern : 
```
111 -> 111.00
11 -> 11.00
1 -> 1.00
0 -> 0.00
0.111 -> 0.11
0.0111 -> 0.011
0.00111 -> 0.0011
0.000111 -> 0.0₃111
```

**Comment by zavelevsky** [comment]
> After discussing with @Costa769 we decided to :
> 
> * Apply full value for tooltip except the one on the strategy card's graph
> * Prices should follow this pattern :
> 
> ```
> 111 -> 111.00
> 11 -> 11.00
> 1 -> 1.00
> 0 -> 0.00
> 0.111 -> 0.11
> 0.0111 -> 0.011
> 0.00111 -> 0.0011
> 0.000111 -> 0.0₃111
> ```

I don't understand `0.111 -> 0.11`  - why remove the last '1'? Same in: `0.0111 -> 0.011`

**Comment by GrandSchtroumpf** [comment]
You need to round it somehow. Maybe this example makes more sense
```
123.4567 -> 123.45
12.34567 -> 12.34
1.234567 -> 1.23
0 -> 0.00
0.1234567 -> 0.12
0.01234567 -> 0.012
0.001234567 -> 0.0012
0.0001234567 -> 0.0₃12345
```

**Comment by zavelevsky** [comment]
OK, this makes more sense now - but I don't get why @ashachaf wanted to make such an exception for subscript.
why it gets 5 more decimals after the subscript but any other small number gets two decimals after the last 0.
e.g. why:
0.001234567 -> 0.0012 BUT 0.0001234567 -> 0.0₃12345

I'd understand 
0.001234567 -> 0.0012 AND 0.0001234567 -> 0.0₃12

or 
0.001234567 -> 0.0012345 AND 0.0001234567 -> 0.0₃12345

**Comment by GrandSchtroumpf** [comment]
I assume the subscript logic was copied from other application.
Also the 2 digits logic has been decided by @Costa769 during our conversations after I show the initial result

**Comment by Costa769** [comment]
Please implement the following logic with 6 decimals in case 0< value <1

123.4567 -> 123.45
12.34567 -> 12.34
1.234567 -> 1.23
1 -> 1.00
0 -> 0.00
0.1234567 -> 0.123456
0.01234567 -> 0.012345
0.001234567 -> 0.001234
0.0001234567 -> 0.0₃12345

**Comment by GrandSchtroumpf** [comment]
If I understand correctly, this is the rule ?
**x >= 0**:
- minimumDigits: 2
- maximumDigits: 2

**0 > x >= 0.001**
- minimumDigits: 2
- maximumDigits: 6

**0.001 > x** (subscript)
- minimumDigits (after subscript): 1
- maximumDigits (after subscript): 5
