### ISSUE TITLE
When updating only one budget the UI shouldn't update the other

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-app#933]
<img width="378" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/672016/0fb0b227-567c-4848-8577-e2b5cfd51bc6">

While testing I noticed that when I deposit to an existing strategy, not an overlapping one, the UI updates both budgets - which is wrong. The user wants to only add USDC but sees in the approval modal that he also approves the other token. Notice in the console how I get sellBudget - it should not be there. This also resets Z.

_Originally posted by @zavelevsky in https://github.com/bancorprotocol/carbon-app/issues/905#issuecomment-1853185032_

**Comment by ashachaf** [comment]
@zavelevsky is this still relevant?

**Comment by pingustar** [comment]
not reproducible anymore. I think this was fixed when we reworked the reset/maintain logic
