### ISSUE TITLE
Strategy creation -  strategyDirection deeplink parameter

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#937]
### Overview
If a specific param is available in a deep link, it should apply specific changes on the create strategy view.

### strategyType
IF strategyType = recurring OR strategyType = overlapping, ignore `strategyDirection` param if exists in the URL.

currently, IF strategyType = recurring AND strategyDirection = sell, the app opens a disposable view but input "recurring" as the type of strategy. 
expected, IF strategyType = recurring AND strategyDirection = sell, the app opens a recurring strategy view with both buy and sell order boxes

### strategyDirection
IF strategyType = disposable AND strategyDirection is not passed, the app should open a view that assumes strategyDirection = buy.

currently, IF strategyType = disposable AND strategyDirection = null, the app opens a recurring view with both orders but input "disposable" as the type of strategy. 
expected, IF strategyType = disposable AND strategyDirection = null, the app opens a disposable strategy view with buy order box

**Comment by ashachaf** [comment]
@Costa769 is this still relevant?
