### ISSUE TITLE
Strategy Creation - Inputs of '.' in token price show NaN values

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/carbon-app#942]
When creating a strategy, inputs of '.' in token price (limit/ranges) show NaN values.

<img width="620" alt="Screenshot 2023-12-14 at 11 33 47" src="https://github.com/bancorprotocol/carbon-app/assets/66181828/8f698df1-6924-4758-abc3-bf07095b6575">

Either hide the text or show a more adequate message.

**Comment by zavelevsky** [comment]
@tiagofilipenunes I believe this was fixed, please confirm.

**Comment by tiagofilipenunes** [comment]
It was fixed by #862
