### ISSUE TITLE
Expose trading and user activity history

### ISSUE THREAD

**Issue by Costa769** [bancorprotocol/carbon-app#955]
# Summary

We aim to provide users with access to both strategy trading data and their own activity history on the platform

# Designs

[My strategies general activity page](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39505&mode=design&t=KvFQN6dQSwe53Nwz-1)
[My strategies/Explorer specific strategy activity page](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A38832&mode=design&t=KvFQN6dQSwe53Nwz-1)
[Explorer general activity page](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A48426&mode=design&t=KvFQN6dQSwe53Nwz-1)
[Explorer overview](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A40611&mode=design&t=KvFQN6dQSwe53Nwz-1)
[My strategies overview card with new activities](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39407&mode=design&t=KvFQN6dQSwe53Nwz-1)
[Filters](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=KvFQN6dQSwe53Nwz-1)
[Date selection](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A40312&mode=design&t=tLa592PQ4tnPAU8f-1)

# Overview

Currently, the carbon app supports advanced strategy management, however it is lacking the visibility of the action taken and performed against these strategies. 

The following data should be available for the users:

1. wallet centric -> the activity here include 2 parts:
_Note this is the same data under "my strategies" viewed as the owner AND under explorer_
- any strategy the wallet owns and interacted with (as an owner). 
- any action done against strategies the wallet owns. 
```
Example:
assume wallet 0x000
0x000 create new strategy -> show under "my strategies" activity
0x000 trade -> IF strategy is NOT owned by wallet 0x000 -> this data is NOT visible on the "my strategies" activity
any wallet trade -> IF strategy is owned by wallet 0x000 -> this data is going to be visible on the "my strategies" activity
```

2. strategy centric -> anything done on the strategy. being owner actions or trade actions.
```
Example:
assume strategy 111
trade (by any wallet) -> IF strategy 111 -> include this activity data under strategy view
edit prices (by any wallet, while it should be limited to owner in the contract level) -> IF strategy 111 ->  include this activity data under strategy view
```

- This activity data will also be available as a downloadable csv file.

- The activity data will be displayed on three pages:
1. Specific strategy activity page: 
Grouped by strategy ID, anyone can access data related to a specific strategy, including its trading data and the user's actions related to that particular strategy. This view is accessible via the strategy overview card (available under "my strategies" and "explorer")
2. Specific pair:
Array of strategy IDs. anyone can access data related to a specific pair (which will result in an array of strategy IDs). "Explorer -> pair -> activity" will display all actions related to the array of strategy IDs.
3. General activity page: 
Grouped by wallet address, anyone can access data related to a specific wallet, including its "owner" activity against strategies and all trade actions done on its strategies. This view is accessible under "my strategies" -> "activity" and "explorer" ->wallet address-> activity

# Specific strategy activity page
This view will be dedicated to a specific strategy. 

How to access this page?
1. My strategies -> strategy overview card -> strategy activity
2. Explorer -> wallet or pair search -> strategy overview card -> strategy activity

_There are some minor differences in the design and functions of the strategy activity page depending on whether the user accessed it from the "My Strategies" or "Explorer" page. These differences will be explained further below._

URL structure:
View URL:
/activity/strategyId=23434

**The page consist of three sections:**

1. Strategy info
Strategy info section will resemble the strategy card from the My strategies page with 1 difference that the menu is moved outside to the page level. (When users hover over the price range in this section, a tooltip will appear, providing the same data that is displayed on the "My Strategies" page.)

2. Price chart
The price chart is the same price chart we show on strategy creation/edit pages
- on "Close" -> center the "strategy info" card

3. Activity table
- The "Activity table" will display a comprehensive list of all activities related to the strategy, encompassing both the strategy trading data and the user's own activities.
- Data is coming from an API endpoint.
- Table show only those activities that their transaction was confirmed on chain.

## Activity table
The activity table will include the following columns:
1. Action - describing the transaction that was done and its human readable meaning
2. Sell budget - indicating the strategy sell budget change 
3. Buy budget - indicating the strategy buy budget change
4. Date - translating the block number into a readable date

### Action column

In the action column we show the list of activities that include both strategy trades and owner activities
[mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39332&mode=design&t=tLa592PQ4tnPAU8f-1)

Activity API:
https://api.carbondefi.xyz/v1/activity

List of activities to show:

#### Strategy activities

- Name: Sell high
Description: [sold base token amount][base token] sold for [bought quote token amount][quote token]. Avg. price: [quote token amount] [quote token]/[base token]

- Name: Buy low
Description: [bought base token amount][base token] bought for [sold quote token amount][quote token]. Avg. price: [quote token amount] [quote token]/[base token]

#### User activities

- Name: Deposit
IF one token was deposited
Description: [deposited token amount][token symbol] was deposited to the strategy.
ELSE, IF two tokens were deposited
Description: [deposited TKN1 amount][TKN1 symbol] and [deposited TKN2 amount ][TKN2 symbol] were deposited to the strategy.

- Name: Withdraw
IF one token was withdrawn
Description: [withdrawn token amount][token symbol] was withdrawn to the wallet.
ELSE, IF two tokens were withdrawn
Description: [withdrawn TKN1 amount][TKN1 symbol] and [withdrawn TKN2 amount ][TKN2 symbol] were withdrawn to the wallet.

- Name: Edit Price
**In case of a limit order**
**IF** Buy token price was edited
Description: Buy [base token symbol] price: [new quote token price][quote token symbol] 
**ELSE, IF** Sell token price was edited
Description: Sell [base token symbol] price: [new quote token price][quote token symbol] 
**ELSE, IF** Both buy and sell  token prices were edited
Description: Buy [base token symbol] price: [new quote token mount][quote token symbol] and Sell [base token symbol] price: [new quote token mount][quote token symbol] 
**In case of a range order**
**IF** Buy token range price was edited
Description: Buy [base token symbol] price: [new quote token min price][quote token symbol] -[new quote token max price][quote token symbol] 
**ELSE, IF** Sell token range price was edited
Description: Sell [base token symbol] price: [new quote token min price][quote token symbol] -[new quote token max price][quote token symbol] 
**ELSE, IF** Both buy and sell token range prices were edited
Buy [base token symbol] price: [new quote token min price][quote token symbol] -[new quote token max price][quote token symbol ] / Sell [base token symbol] price: [new quote token min price][quote token symbol] -[new quote token max price][quote token symbol] 

- Name: Create Strategy
Description-> Use the same logic as for Edit price above

- Name: Pause Strategy
Description: The strategy was paused

- Name:  Transfer strategy
Description: The strategy was transferred

Note that in case of a strategy NFT transfer between two wallets, both the sender and receiver wallets will have the transfer activity displayed in a designated strategy activity table and the activity tab.

### Buy/Sell budget columns

Both buy and sell budget columns display the budgets of the strategy after the action was completed and confirmed on chain.

Below the budget, show the change in the budget following the action.

- **IF** the change in budget is negative, display the amount in red.
- **ELSE, IF** the change in budget is positive, display the amount in green.
- **ELSE, IF** there is no change, show "..." to indicate that there is no change in the budget.

```
Example:
Given strategy buy budget: 1 ETH 
User deposited 2 ETH to the buy budget
Buy budget column will show an updated buy budget of 3 ETH (1 ETH+ 2 ETH) and “+2 ETH” in green below the updated buy budget
```
[mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A38832&mode=design&t=tLa592PQ4tnPAU8f-1)

### Date column

Shows the date when the transaction was confirmed on blockchain

- Below the date show the transaction hash
- On click open etherscan page with transaction details in a new tab 

### Activity table filters and settings 

[filter mockups](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=tLa592PQ4tnPAU8f-1)

**Activity filter**
Allows the user to filter the table by activity type
- On click -> Show dropdown list of both all user and trade activities
-- The list of activities is static, meaning it doesn't change dynamically, and it displays all activities irrespective of whether the user/strategy has executed them or not. 
- Search input field behavior resembles the behavior of the token pair input field on the explorer page

**Filter selection logic**

- Activity dropdown list supports multiple selections
- Default view-> show all activities (no specific activity is selected from the list) [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=pSWj4nZsgGv9fPIZ-1)
- User can select activity from the list by clicking on the activity name or the checkbox next to it
- **IF** at least one of the activities is selected
-- Show reset filter CTA below the search field [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Yvq6t5O5gFQJqhBY-1)
--- On “reset filter” click -> return to the default view state [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=pSWj4nZsgGv9fPIZ-1)
- Show results in the activity table
-- **IF** no selected activity was found- show an empty activity table with corresponding text (mockup)

**Date filter**
Allows the user to filter the table by date range

- On click -> Show a date selection dropdown
- Date range selection filter should have a behavior similar to the one found in this link. https://ui.shadcn.com/docs/components/date-picker 
- Default selection-> all dates selected [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A40312&mode=design&t=Lhfile3EhCq51bJr-1)
-- Specific date selected [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A40312&mode=design&t=Lhfile3EhCq51bJr-1)
-- Date range selected [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A40312&mode=design&t=Lhfile3EhCq51bJr-1)
- Button functions and preselected option description -TBD

**Export to excel**
Allows the user to export all  the data in the table to CVS file

- On click-> export the table data to CSV file and download it. 
- The CSV file should include all the activity table columns + show Txhash, Blockno  and DateTimeUTC columns similar to Etherscan CSV file format 
- Example: https://etherscan.io/exportData?type=address&a=0x6196ad64a30e469c7a10e474fa8613047086501d 

**Countdown timer**
The page data (in the activity table) should update frequently. To indicate it is updating, there would be a 30 sec counter that:
- On page load, and fresh data is fetched, display a 30-second countdown timer that will start counting down to 0
- Once the timer reaches 0:
-- Refresh the data in the activity table.
-- Reset the timer to 30 seconds and continue the countdown.
- If user refreshes the page, the counter will be reset to 30 seconds and will continue the countdown

**Table settings**

- Display 10 activities on page by default
- Sort the "Activity table" by the date column in descending order, from the latest action at the top to the earliest action at the bottom
- Table is not sortable by clicking on the column headers

	
**Manage button**

The menu changes based on the connected wallet. Its identical to how we do in the explorer/my strategies view
- The menu button behavior is the same as for the menu gear icon on the strategy overview card
- On click, open a menu with the same options that are available for this strategy in the overview card menu dropdown based on the viewing wallet (same restrictions applied on my strategies vs explorer) page.
- Use the same open/close animations we currently use for a manage menu
- Any click outside of the open menu will close it(same as gear icon menu behavior)
- Use the same tooltips when mouse hover over the menu options

### New activity indication in the Activity table & Strategy overview card

We aim to give users a noticeable indication on both the strategy overview card and in the activity table, signaling whether there have been new trades in a specific strategy since their last visit to the platform. 
[mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39407&mode=design&t=KvFQN6dQSwe53Nwz-1)

Strategy overview cards on Explorer page shouldn't display the new activity indication

**New activity indication logic** 

- The strategy overview card will display the number of new strategy trades since the last visit next to the activity icon. [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39407&mode=design&t=JP3PtA59cRR2btR9-1)
- The displayed number will exclude the user's own activity.
- Opening the strategy activity page will highlight the rows of new trades that occurred. [mockup 1](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=12541%3A53452&mode=design&t=JP3PtA59cRR2btR9-1), [mockup 2](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=12541%3A53453&mode=design&t=JP3PtA59cRR2btR9-1)
- Upon returning to the "My Strategies" view from the strategy activity page, the number indication next to the activity icon will be hidden.
- If there are multiple pages of new trades and the user only views the first page, the number next to the activity icon will represent the total number of new activities the user hasn't seen.
- On page load/when the activity table is refreshed every 30 seconds, in case there are new activities to show , apply the following animation 
https://github.com/bancorprotocol/carbon-app/assets/127974452/def12eb4-3c48-4878-9334-8e7ad8e860ee

# Pair activity page
This is a unique page as it follow the "General" activity page design, that filters and displays strategies based on the selected pair.

# General activity page
This page will only expose the activity data (unlike the strategy activity where we will show the strategy overview card as well).

How can a user reach this page?
1. My strategies -> tab options "overview, portfolio, activity" -> select "activity"
2. Explorer -> search wallet or pair -> tab options "overview, portfolio, activity" -> select "activity"
[mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39505&mode=design&t=tLa592PQ4tnPAU8f-1)

URL structure:
View URL:
/activity

The activity tab comprises one activity table section. While table UI and functionality are similar to the activity table on a specific strategy activity page described above, there are a few distinctions:

- In order to distinguish between different strategies, we will show a strategy ID column, also containing both base and quote tokens.
- Show both ID and token pair filters
- Show a delete strategy activity in the table

**ID filter**
Allows the user to filter the table by strategy ID

- On click -> Show dropdown list of all the strategy IDs on the platform
- The behavior of the ID dropdown selection list and search input field is similar to the behavior of the activity filter selection list and search fields.
-- Search input not found [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Lhfile3EhCq51bJr-1) 
- Selection result display logic are the same as for the activity filter 
-- Default selection-> show all strategy IDs [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Lhfile3EhCq51bJr-1)
-- Filter selected [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Lhfile3EhCq51bJr-1)

**Token pair filter**
Allows the user to filter the table by token pair

- On click -> Show dropdown list of all the token pairs on the platform
- The behavior of the token pair dropdown selection list and search input field is similar to the behavior of the activity filter selection list and search fields.
-- Search input not found [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Lhfile3EhCq51bJr-1) 
- Selection logic is the same as for the activity filter 
--Default selection-> show all pairs [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Lhfile3EhCq51bJr-1)
-- Filter selected [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=11573%3A39885&mode=design&t=Lhfile3EhCq51bJr-1)

**Delete strategy activity**

Show a delete strategy activity in the action column in the activity table 

Name: Delete strategy
Description: The strategy was deleted

## Important notes
- We won't show token approval transactions in the activity table
- We won't show user own trades as a separate activity in the activity table. Meaning, If a user goes to a trade page and executes a trade, the system will distinguish between two scenarios:
**Scenario 1-**  user trades against their own strategy:
-- Display the corresponding strategy activity (buy low/sell high)  under both the "My Strategies" and "Explorer" activity tabs.
**Scenario 2**-  user trades against someone else's strategy:
-- Do not show any activity under the activity tab on the "My Strategies" page.
-- Display the corresponding strategy activity (buy low/sell high) under the activity tab on the "Explorer" page.
- As some of our partners may prefer not to fork our backend and may lack data for the activity table, we want to ensure users can still access the specific strategy page even in the absence of activity data. Therefore, in case the activity data is  missing, the following rules should be applied:
-- Show activity icon on the strategy overview card on both My strategies and Explorer pages
--- On click open a strategy activity page without the strategy activity table [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=13222%3A107162&mode=design&t=ANWP9lra8jYkl08M-1)
-- Do not show activity tab on both My strategies and Explorer pages

```
Examples:

1- Assume wallet 0x000 creates/duplicates new strategy 111

Show create strategy activity on
1. My strategies activity tab for wallet 0x000
2. Strategy 111 activity page
3. Explorer activity tab when wallet 0x000 view or strategy 111 token pair view are selected 

2- Assume wallet 0x000 edits prices/deposits/withdraws from strategy 111

Show edit prices/deposit/withdraw activity on
1. My strategies activity tab for wallet 0x000
2. Strategy 111 activity page
3. Explorer activity tab when wallet 0x000 view or strategy 111 token pair view are selected 


3- Assume wallet 0x000 goes to trade page and trades against strategy 111

Show Buy low/Sell high activity on
1. My strategies activity tab for wallet 0x000
2. Strategy 111 activity page
3. Explorer activity tab when wallet 0x000 view or strategy 111 token pair view are selected 


4- Assume wallet 0x000 goes to trade page and trades against strategy 222 (this strategy is not owned by wallet 0x000)

Show Buy low/Sell high activity on
1. Strategy 222 activity page
2. Explorer activity tab when wallet 0x000 view or strategy 222 token pair view is selected
My strategies activity page for  wallet 0x000 won't show Buy low/Sell high activity
 
5- Assume wallet 0x222 goes to trade page and trades against strategy 111 (this strategy is owned by wallet 0x000)

Show Buy low/Sell high activity on
1. My strategies activity tab for wallet 0x000
2. Strategy 111 activity page
3. Explorer activity tab when wallet 0x000 or wallet 0x222 view or strategy 111 token pair view are selected 


6- Assume wallet 0x000 deletes strategy 111

Show delete strategy activity on
1. My strategies activity tab
2. Explorer activity tab IF wallet 0x000 view or strategy 111 token pair view is selected 
Since the strategy 111 is deleted, strategy 111 activity page can't be accessed

7- Assume wallet 0x000 transfers strategy 111 to wallet 0x333

Show transfer strategy activity on
1. My strategies activity tab for both wallet 0x000 and wallet 0x333
2. Strategy 111 activity page
4. Explorer activity tab when wallet 0x000 or wallet 0x333 view or strategy 111 token pair view are selected 

```

**Comment by GrandSchtroumpf** [comment]
- [ ] Token icons-> token icons design in the activity table not yet implemented
- [x] Filter & sort dropdown menu-> remove from both activities and portfolio tabs
- [ ] Add “+” to the positive  value changes in budget columns
- [ ] Lets try arrange the columns width in a way that the date and most of the amounts under budgets(not counting the extreme cases) will be in one row, we can make the description text in 2 rows
- [ ] “Select date range”->”Select Date Range”
- [ ] It's hard to distinguish between the collapsed filter with and without selected items. I’ll provide you with a design to implement for a collapsed filter with selected items to make it more noticeable 
- [ ] Missing Export +Timer
- [ ] There is a strange behavior with the date picker. Open a date picker select one day and click on confirm -> dates in the activity table change not according to the date selected and there is  no indication to the selected date in the collapsed date picker
- [ ] Currently for each Create or Delete strategy activity we also show a Transfer activity for this strategy, since the NFT is transferred to the wallet address from the contract when strategy is created and when deleted-> we should filter this contract related  NFT transfer activity out and do not display it in the activity table
- [ ] We should add a table generation animation.I’m not talking about data loading, we have a carbon head animation for that but a table rows populate animation that looks cool(as we did with the pie chart in the portfolio section). I’ll look for something but if you have any ideas feel free to suggest
- [ ] How can the user select all his specific pair strategies? We might need to add a pair selection filter as on design since the strategy filter is not enough

**Comment by Costa769** [comment]
- [ ] In case of a subscript number in the activity table show a full number in regular format in the downloaded excel file
- [ ] When user selects a single date from the date picker and confirms his selection, the collapsed date picker show 2 selected dates
- [ ] Add a green border to the collapsed date picker once a selection that is not default applied (same as with other filters)
- [ ] On the specific strategy activity page replace manage icon with manage button [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=12140%3A37707&mode=design&t=51h6hCh0ZXt5vvvE-1)
- [ ] On a specific strategy activity page when the user that doesn't own the strategy clicks on manage icon he sees deposit/withdraw/edit/pause and delete options that are not supposed to be visible only to an owner
- [ ] Remove "manage notification" option from the strategy manage menu on all pages
- [ ] Sort actions in the activity table by date->descending (the last date on top)

**Comment by Costa769** [comment]
- [ ] On explorer page , when user selects a pair and then clicks on the activity tab, he sees a "No activities found" page for a sec and then the activities are shown in the table
- [ ] "View Owner's strategies" option is missing in the manage strategy menu in the specific strategy activity page
- [ ] Change the font of the Date rows in the activity table->date column from Mono to GT America [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=12140%3A37707&mode=design&t=r1RznbfLTMnVsuYR-1)

**Comment by Costa769** [comment]
- [ ] ID column is missing from activity table on  My strategies->Activity tab
- [ ] Change Strategies and Actions collapsed filters titles in the activity table:
- Select Strategies -> Filter Strategies
- Select Actions-> Filter Actions
- [ ] Action column descriptions
1. In case of Buy Low or Sell High actions the token that is bought or sold should be the base token denominated in the quote token. In case of Edit prices action both Base token buy and sell prices should also be denominated in quote token
For example in the screenshot below the description should be:

- Buy low-> 2.22 ETH was bought for 7,458.57 USDC. Avg price: 3,349.99 USDC/ETH. 
- Edit Prices-> Buy ETH: 3,349.99 USDC / Sell ETH: 100,000.00 USDC.
- Sell High-> In this case we should display the sold amount of Base token (ETH) for Quote token amount (USDC). The price should be also displayed as the amount of USDC per 1 ETH

![image](https://github.com/bancorprotocol/carbon-app/assets/127974452/f94033ee-8556-419d-9e98-05026e71d40d)
