### ISSUE TITLE
[Create Strategy] Refactor creation form

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#992]
## Problem
We currently use a single page with `order0` & `order1` object as a source of truth.
With the overlapping strategy, the pattern start diverging which make it difficult to maintain as a single source. Calculus automation in the overlapping strategy also create a new difficulty that wasn't there before.

This is the good time for a refactoring 😎

## Solution (to be validated)
- Create one page per type: "disposable", "recurring", "overlapping"
- Use URL's search params as a source of truth (sync form & url)
- Consider using [useFormState](https://react.dev/reference/react-dom/hooks/useFormState) & [useFormStatus](https://react.dev/reference/react-dom/hooks/useFormStatus) and [form](https://react.dev/reference/react-dom/components/form) from React to manage state & status

**Comment by tiagofilipenunes** [comment]
#930
